# version: '3.8'

# services:
#   webui:
#     build:
#       context: .
#       dockerfile: Dockerfile.web
#     ports:
#       - "5173:5173"
#     volumes:
#       - ./:/app
#       - /app/node_modules
#     environment:
#       - VITE_API_URL=http://localhost:3000
#     command: npm run dev -- --host 0.0.0.0 # 添加这行，允许外部访问
#     depends_on:
#       - server

#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./server:/app
#       - /app/node_modules
#     command: npm run start:prod -- --host 0.0.0.0

# networks:
#   default:
#     driver: bridge

version: '3.8'

services:
  webui:
    image: zhouxin98/esaypwm-webui:latest
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - server

  server:
    image: esaypwm-server:latest
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run start:prod -- --host 0.0.0.0

networks:
  default:
    driver: bridge
